const LESSONS = {
  "structures-1": {
    id: "structures-1",
    title: "Structures Clés",
    subtitle: "Would, Could, Should",
    icon: "🏗️",
    color: "#3b82f6",
    questionCount: 25,
    theoryPage: "theory-structures.html",
    hasQuiz: true,
    questions: [
      {fr:"Je voudrais un café, s'il vous plaît.",en:["I would like a coffee, please."],structure:1},
      {fr:"Est-ce que tu voudrais venir avec nous ?",en:["Would you like to come with us?"],structure:1},
      {fr:"Il aimerait apprendre le piano.",en:["He would like to learn the piano.","He would love to learn the piano."],structure:1,variantNote:"Même sens — <em>love</em> exprime une intensité légèrement plus forte que <em>like</em>."},
      {fr:"Nous voudrions réserver une table pour ce soir.",en:["We would like to book a table for tonight.","We would like to reserve a table for tonight."],structure:1,variantNote:"Synonymes — <em>book</em> et <em>reserve</em> signifient tous les deux réserver, aucune différence de sens."},
      {fr:"Elle préférerait rester à la maison.",en:["She would prefer to stay at home.","She would rather stay at home."],structure:1,variantNote:"Même sens, construction différente — <em>would prefer + to + verbe</em>, mais <em>would rather + infinitif sans to</em>."},
      {fr:"Je veux vraiment aller à Paris un jour.",en:["I would really like to go to Paris one day.","I really want to go to Paris one day."],structure:1,variantNote:"Légère différence de registre — <em>would like</em> est plus poli et formel, <em>want</em> est plus direct et décontracté."},
      {fr:"Ils voudraient un remboursement.",en:["They would like a refund."],structure:1},
      {fr:"Est-ce que vous voudriez quelque chose à boire ?",en:["Would you like something to drink?"],structure:1},
      {fr:"J'aimerais vraiment te voir bientôt.",en:["I would really like to see you soon.","I would love to see you soon."],structure:1,variantNote:"Même sens — <em>love</em> ajoute une touche d'enthousiasme plus forte, mais les deux sont tout à fait correctes."},
      {fr:"Pourriez-vous m'aider, s'il vous plaît ?",en:["Could you help me, please?"],structure:2},
      {fr:"Est-ce que tu pourrais fermer la fenêtre ?",en:["Could you close the window?","Could you please close the window?"],structure:2,variantNote:"Aucune différence — <em>please</em> renforce simplement la politesse, il est optionnel."},
      {fr:"Serait-il possible de changer ma réservation ?",en:["Could I change my reservation?","Would it be possible to change my reservation?"],structure:2,variantNote:"<em>Could I…</em> est direct et courant. <em>Would it be possible…</em> est plus formel, souvent utilisé dans un contexte professionnel."},
      {fr:"Pourriez-vous parler plus lentement ?",en:["Could you speak more slowly?","Could you please speak more slowly?"],structure:2,variantNote:"Aucune différence — <em>please</em> est optionnel, il renforce la politesse."},
      {fr:"Est-ce que je pourrais avoir l'addition ?",en:["Could I have the bill?","Could I get the check?"],structure:2,variantNote:"Différence géographique uniquement — <em>bill</em> est anglais britannique, <em>check</em> est américain. Même sens !"},
      {fr:"Ce serait bien si tu pouvais venir.",en:["It would be nice if you could come."],structure:2},
      {fr:"Pourrait-il rappeler plus tard ?",en:["Could he call back later?"],structure:2},
      {fr:"Est-ce que tu pourrais me prêter ton stylo ?",en:["Could you lend me your pen?","Could you borrow me your pen?"],structure:2,variantNote:"<em>lend</em> = prêter (tu donnes), <em>borrow</em> = emprunter (tu reçois). Ici <em>lend me</em> est la formulation correcte — <em>Could you borrow me</em> n'est pas standard en anglais."},
      {fr:"J'aurais dû étudier plus tôt.",en:["I should have studied earlier."],structure:3},
      {fr:"Il aurait dû appeler avant de venir.",en:["He should have called before coming."],structure:3},
      {fr:"Nous aurions dû prendre un parapluie.",en:["We should have taken an umbrella.","We should have brought an umbrella."],structure:3,variantNote:"Très proches — <em>taken</em> (pris) vs <em>brought</em> (apporté/amené). <em>Brought</em> est légèrement plus naturel car on insiste sur le fait d'amener l'objet avec soi."},
      {fr:"Tu n'aurais pas dû dire ça.",en:["You should not have said that.","You shouldn't have said that."],structure:3,variantNote:"Aucune différence — <em>shouldn't</em> est la contraction de <em>should not</em>, plus courante à l'oral."},
      {fr:"Elle aurait dû partir plus tôt.",en:["She should have left earlier."],structure:3},
      {fr:"Ils auraient dû lire les instructions.",en:["They should have read the instructions."],structure:3},
      {fr:"J'aurais dû me souvenir de son anniversaire.",en:["I should have remembered her birthday.","I should have remembered his birthday."],structure:3,variantNote:"Aucune différence de sens — <em>her</em> = son (féminin), <em>his</em> = son (masculin). Dépend de la personne dont tu parles."},
      {fr:"On aurait dû réserver à l'avance.",en:["We should have booked in advance.","We should have reserved in advance."],structure:3,variantNote:"Synonymes — <em>book</em> et <em>reserve</em> signifient tous les deux réserver, aucune différence de sens."}
    ]
  },
  "pp-hub": {
    id: "pp-hub",
    title: "Participe Passé",
    subtitle: "Structures, voix passive & verbes irréguliers",
    icon: "⏪",
    color: "#10b981",
    theoryPage: "pp-hub.html",
    hasQuiz: true
  },
  "past-participle-1": {
    id: "past-participle-1", hidden: true,
    title: "Participe Passé",
    subtitle: "Formation & 4 structures essentielles",
    icon: "⏪",
    color: "#10b981",
    questionCount: 20,
    theoryPage: "theory-past-participle.html",
    hasQuiz: true,
    questions: [
      {fr:"J'ai mangé.",en:["I have eaten."],structure:4},
      {fr:"Elle a fini son travail.",en:["She has finished her work."],structure:4},
      {fr:"Il a cassé la fenêtre.",en:["He has broken the window."],structure:4},
      {fr:"Tu as oublié tes clés.",en:["You have forgotten your keys."],structure:4},
      {fr:"Nous avons pris notre décision.",en:["We have made our decision.","We have taken our decision."],structure:4,variantNote:"<em>make a decision</em> est plus naturel en anglais courant, <em>take a decision</em> est aussi correct."},
      {fr:"Il avait déjà mangé quand je suis arrivé.",en:["He had already eaten when I arrived."],structure:5},
      {fr:"Elle avait étudié toute la nuit.",en:["She had studied all night."],structure:5},
      {fr:"Nous avions déjà vu ce film.",en:["We had already seen this movie.","We had already seen this film."],structure:5,variantNote:"Aucune différence — <em>movie</em> est américain, <em>film</em> est britannique."},
      {fr:"Ils n'avaient jamais voyagé à l'étranger.",en:["They had never travelled abroad.","They had never traveled abroad."],structure:5,variantNote:"Aucune différence — <em>travelled</em> est l'orthographe britannique, <em>traveled</em> est américaine."},
      {fr:"Tu aurais dû appeler.",en:["You should have called."],structure:6},
      {fr:"Elle aurait pu venir.",en:["She could have come."],structure:6},
      {fr:"Il a dû oublier son rendez-vous.",en:["He must have forgotten his appointment."],structure:6},
      {fr:"Nous aurions pu rester.",en:["We could have stayed."],structure:6},
      {fr:"Elle aurait dû savoir.",en:["She should have known."],structure:6},
      {fr:"La fenêtre a été cassée.",en:["The window was broken."],structure:7},
      {fr:"La lettre a été envoyée.",en:["The letter was sent."],structure:7},
      {fr:"Le livre a été écrit en 1984.",en:["The book was written in 1984."],structure:7},
      {fr:"Le repas est préparé.",en:["The meal is prepared."],structure:7},
      {fr:"La décision a été prise.",en:["The decision was made.","The decision was taken."],structure:7,variantNote:"Même sens — <em>made</em> est plus courant, <em>taken</em> aussi correct."},
      {fr:"Les instructions n'ont pas été suivies.",en:["The instructions were not followed.","The instructions weren't followed."],structure:7,variantNote:"Aucune différence — <em>weren't</em> est la contraction de <em>were not</em>."}
    ]
  },
  "irreg-verbs-1": {
    id:"irreg-verbs-1",hidden:true,title:"Verbes irréguliers — Groupe 1",subtitle:"⚠️ V1 / V2 / V3 — 3 formes différentes",icon:"⚠️",color:"#f59e0b",questionCount:10,hasQuiz:true,
    questions:[
      {fr:"casser",en:["break / broke / broken"],combined:true},
      {fr:"manger",en:["eat / ate / eaten"],combined:true},
      {fr:"aller",en:["go / went / gone"],combined:true},
      {fr:"voir",en:["see / saw / seen"],combined:true},
      {fr:"prendre",en:["take / took / taken"],combined:true},
      {fr:"écrire",en:["write / wrote / written"],combined:true},
      {fr:"parler",en:["speak / spoke / spoken"],combined:true},
      {fr:"savoir / connaître",en:["know / knew / known"],combined:true},
      {fr:"donner",en:["give / gave / given"],combined:true},
      {fr:"boire",en:["drink / drank / drunk"],combined:true}
    ]
  },
  "irreg-verbs-1b": {
    id:"irreg-verbs-1b",hidden:true,title:"Verbes irréguliers — Groupe 1b",subtitle:"⚠️ V1 / V2 / V3 — 3 formes différentes",icon:"⚠️",color:"#ef4444",questionCount:20,hasQuiz:true,
    questions:[
      {fr:"être",en:["be / was / been","be / were / been"],combined:true},
      {fr:"devenir",en:["become / became / become"],combined:true},
      {fr:"commencer",en:["begin / began / begun"],combined:true},
      {fr:"choisir",en:["choose / chose / chosen"],combined:true},
      {fr:"venir",en:["come / came / come"],combined:true},
      {fr:"faire",en:["do / did / done"],combined:true},
      {fr:"dessiner",en:["draw / drew / drawn"],combined:true},
      {fr:"conduire",en:["drive / drove / driven"],combined:true},
      {fr:"tomber",en:["fall / fell / fallen"],combined:true},
      {fr:"voler",en:["fly / flew / flown"],combined:true},
      {fr:"oublier",en:["forget / forgot / forgotten"],combined:true},
      {fr:"grandir / pousser",en:["grow / grew / grown"],combined:true},
      {fr:"monter (vélo/cheval)",en:["ride / rode / ridden"],combined:true},
      {fr:"courir",en:["run / ran / run"],combined:true},
      {fr:"montrer",en:["show / showed / shown"],combined:true},
      {fr:"chanter",en:["sing / sang / sung"],combined:true},
      {fr:"nager",en:["swim / swam / swum"],combined:true},
      {fr:"lancer",en:["throw / threw / thrown"],combined:true},
      {fr:"réveiller",en:["wake / woke / woken"],combined:true},
      {fr:"porter",en:["wear / wore / worn"],combined:true}
    ]
  },
  "irreg-verbs-2": {
    id:"irreg-verbs-2",hidden:true,title:"Verbes irréguliers — Groupe 2",subtitle:"✅ V2 = V3 — passé simple = participe passé",icon:"🟩",color:"#10b981",questionCount:20,hasQuiz:true,
    questions:[
      {fr:"apporter",en:["bring / brought / brought"],combined:true},
      {fr:"construire",en:["build / built / built"],combined:true},
      {fr:"acheter",en:["buy / bought / bought"],combined:true},
      {fr:"attraper",en:["catch / caught / caught"],combined:true},
      {fr:"ressentir",en:["feel / felt / felt"],combined:true},
      {fr:"trouver",en:["find / found / found"],combined:true},
      {fr:"avoir",en:["have / had / had"],combined:true},
      {fr:"entendre",en:["hear / heard / heard"],combined:true},
      {fr:"garder",en:["keep / kept / kept"],combined:true},
      {fr:"partir / laisser",en:["leave / left / left"],combined:true},
      {fr:"perdre",en:["lose / lost / lost"],combined:true},
      {fr:"faire / fabriquer",en:["make / made / made"],combined:true},
      {fr:"rencontrer",en:["meet / met / met"],combined:true},
      {fr:"payer",en:["pay / paid / paid"],combined:true},
      {fr:"dire",en:["say / said / said"],combined:true},
      {fr:"vendre",en:["sell / sold / sold"],combined:true},
      {fr:"envoyer",en:["send / sent / sent"],combined:true},
      {fr:"dire / raconter",en:["tell / told / told"],combined:true},
      {fr:"penser",en:["think / thought / thought"],combined:true},
      {fr:"gagner",en:["win / won / won"],combined:true}
    ]
  },
  "irreg-verbs-2b": {
    id:"irreg-verbs-2b",hidden:true,title:"Verbes irréguliers — Groupe 2b",subtitle:"✅ V2 = V3 — passé simple = participe passé",icon:"🟩",color:"#059669",questionCount:10,hasQuiz:true,
    questions:[
      {fr:"obtenir",en:["get / got / got"],combined:true},
      {fr:"tenir",en:["hold / held / held"],combined:true},
      {fr:"prêter",en:["lend / lent / lent"],combined:true},
      {fr:"lire",en:["read / read / read"],combined:true},
      {fr:"s'asseoir",en:["sit / sat / sat"],combined:true},
      {fr:"dormir",en:["sleep / slept / slept"],combined:true},
      {fr:"dépenser / passer",en:["spend / spent / spent"],combined:true},
      {fr:"se lever / rester debout",en:["stand / stood / stood"],combined:true},
      {fr:"enseigner",en:["teach / taught / taught"],combined:true},
      {fr:"comprendre",en:["understand / understood / understood"],combined:true}
    ]
  },
  "irreg-verbs-3": {
    id:"irreg-verbs-3",hidden:true,title:"Verbes irréguliers — Groupe 3",subtitle:"🟢 V1 = V2 = V3 — 3 formes identiques",icon:"🟢",color:"#22c55e",questionCount:5,hasQuiz:true,
    questions:[
      {fr:"couper",en:["cut / cut / cut"],combined:true},
      {fr:"laisser / permettre",en:["let / let / let"],combined:true},
      {fr:"mettre",en:["put / put / put"],combined:true},
      {fr:"régler / poser",en:["set / set / set"],combined:true},
      {fr:"fermer",en:["shut / shut / shut"],combined:true}
    ]
  },
  "pp-present-perfect": {
    id:"pp-present-perfect",hidden:true,title:"Present Perfect",subtitle:"have / has + participe passé",icon:"✅",color:"#10b981",questionCount:12,theoryPage:"theory-pp-present-perfect.html",hasQuiz:true,
    questions:[
      {fr:"Je n'ai jamais mangé de sushis.",en:["I have never eaten sushi."],structure:4},
      {fr:"Elle a déjà visité Paris.",en:["She has already visited Paris."],structure:4},
      {fr:"Il a perdu ses clés.",en:["He has lost his keys."],structure:4},
      {fr:"Nous avons terminé le projet.",en:["We have finished the project."],structure:4},
      {fr:"Tu n'as pas encore appelé.",en:["You have not called yet.","You haven't called yet."],structure:4,variantNote:"Aucune différence — <em>haven't</em> est la contraction de <em>have not</em>."},
      {fr:"Ils ont déjà vu ce film.",en:["They have already seen this movie.","They have already seen this film."],structure:4,variantNote:"Aucune différence — <em>movie</em> est américain, <em>film</em> est britannique."},
      {fr:"Elle a écrit trois livres.",en:["She has written three books."],structure:4},
      {fr:"J'ai cassé mon téléphone.",en:["I have broken my phone."],structure:4},
      {fr:"Il a conduit toute la nuit.",en:["He has driven all night."],structure:4},
      {fr:"Elle a rencontré quelqu'un.",en:["She has met someone."],structure:4},
      {fr:"Ils ont construit une maison.",en:["They have built a house."],structure:4},
      {fr:"J'ai pris ma décision.",en:["I have made my decision.","I have taken my decision."],structure:4,variantNote:"<em>make a decision</em> est plus naturel en anglais, <em>take a decision</em> est aussi accepté."}
    ]
  },
  "pp-past-perfect": {
    id:"pp-past-perfect",hidden:true,title:"Past Perfect",subtitle:"had + participe passé — plus-que-parfait",icon:"⏮️",color:"#6366f1",questionCount:10,theoryPage:"theory-pp-past-perfect.html",hasQuiz:true,
    questions:[
      {fr:"Il avait déjà mangé quand je suis arrivé.",en:["He had already eaten when I arrived."],structure:5},
      {fr:"Elle n'avait jamais conduit avant.",en:["She had never driven before."],structure:5},
      {fr:"Ils avaient tout vendu avant notre arrivée.",en:["They had sold everything before we arrived."],structure:5},
      {fr:"J'avais déjà vu ce film.",en:["I had already seen this movie.","I had already seen this film."],structure:5,variantNote:"Aucune différence — <em>movie</em> est américain, <em>film</em> est britannique."},
      {fr:"Il avait oublié son mot de passe.",en:["He had forgotten his password."],structure:5},
      {fr:"Nous avions fini avant midi.",en:["We had finished before noon."],structure:5},
      {fr:"Elle avait parlé au directeur.",en:["She had spoken to the manager.","She had spoken to the director."],structure:5,variantNote:"Même sens — <em>manager</em> est plus courant en anglais professionnel, <em>director</em> aussi correct."},
      {fr:"Tu avais pris le mauvais train.",en:["You had taken the wrong train."],structure:5},
      {fr:"Ils n'avaient jamais entendu ce nom.",en:["They had never heard that name.","They had never heard this name."],structure:5,variantNote:"Aucune différence de sens — <em>that</em> ou <em>this</em> fonctionnent tous les deux."},
      {fr:"J'avais perdu mes notes.",en:["I had lost my notes."],structure:5}
    ]
  },
  "pp-modal-have": {
    id:"pp-modal-have",hidden:true,title:"Modal + have",subtitle:"should / could / must + have + PP",icon:"🎯",color:"#f59e0b",questionCount:10,theoryPage:"theory-pp-modal-have.html",hasQuiz:true,
    questions:[
      {fr:"J'aurais dû rester à la maison.",en:["I should have stayed at home."],structure:6},
      {fr:"Tu aurais pu appeler avant de venir.",en:["You could have called before coming."],structure:6},
      {fr:"Elle aurait dû partir plus tôt.",en:["She should have left earlier."],structure:6},
      {fr:"Il a dû se perdre.",en:["He must have gotten lost.","He must have got lost."],structure:6,variantNote:"<em>gotten</em> est américain, <em>got</em> est britannique — les deux sont corrects."},
      {fr:"Nous aurions pu trouver un taxi.",en:["We could have found a taxi."],structure:6},
      {fr:"Tu n'aurais pas dû dire ça.",en:["You should not have said that.","You shouldn't have said that."],structure:6,variantNote:"Aucune différence — <em>shouldn't</em> est la contraction de <em>should not</em>."},
      {fr:"Elle aurait pu réussir.",en:["She could have succeeded."],structure:6},
      {fr:"Ils auraient dû lire les instructions.",en:["They should have read the instructions."],structure:6},
      {fr:"J'aurais dû savoir.",en:["I should have known."],structure:6},
      {fr:"Il a dû prendre le mauvais chemin.",en:["He must have taken the wrong road.","He must have taken the wrong way."],structure:6,variantNote:"Même sens — <em>road</em> et <em>way</em> sont tous deux corrects dans ce contexte."}
    ]
  },
  "pp-passive": {
    id:"pp-passive",hidden:true,title:"Voix passive",subtitle:"be + participe passé",icon:"🔄",color:"#ec4899",questionCount:50,theoryPage:"theory-pp-passive.html",hasQuiz:true,
    questions:[
      {fr:"La fenêtre a été cassée.",en:["The window was broken."],structure:7,explain:{why:"On ne sait pas qui a cassé la fenêtre — ou ce n'est pas important. La fenêtre est le sujet qui <em>subit</em> l'action, pas celui qui agit.",active:{en:"Someone broke the window.",fr:"Quelqu'un a cassé la fenêtre."}}},
      {fr:"La lettre a été envoyée hier.",en:["The letter was sent yesterday."],structure:7,explain:{why:"PP de <em>send</em> : <strong>sent</strong> (irrégulier : send → sent → sent). <em>Yesterday</em> confirme qu'on est au passé simple.",active:{en:"Someone sent the letter yesterday.",fr:"Quelqu'un a envoyé la lettre hier."}}},
      {fr:"Le livre a été écrit en 1984.",en:["The book was written in 1984."],structure:7,explain:{why:"PP de <em>write</em> : <strong>written</strong> (irrégulier). On met le livre en valeur — peu importe QUI l'a écrit.",active:{en:"Someone wrote the book in 1984.",fr:"Quelqu'un a écrit le livre en 1984."}}},
      {fr:"Le repas est servi.",en:["The meal is served."],structure:7,explain:{why:"Présent simple passif : <strong>is + PP</strong>. <em>served</em> est régulier (serve → served). Phrase typique dans un restaurant — phrase courte, impact fort.",active:{en:"The waiter serves the meal.",fr:"Le serveur sert le repas."}}},
      {fr:"La voiture a été vendue.",en:["The car was sold."],structure:7,explain:{why:"PP de <em>sell</em> : <strong>sold</strong> (irrégulier : sell → sold → sold). On met la voiture en avant — qui l'a vendue ? Sans importance.",active:{en:"Someone sold the car.",fr:"Quelqu'un a vendu la voiture."}}},
      {fr:"Le voleur a été attrapé.",en:["The thief was caught."],structure:7,explain:{why:"PP de <em>catch</em> : <strong>caught</strong> (irrégulier). <strong>thief</strong> = voleur — à retenir ! C'est le voleur qui compte ici, pas ceux qui l'ont arrêté.",active:{en:"The police caught the thief.",fr:"La police a attrapé le voleur."}}},
      {fr:"La maison a été construite en 1990.",en:["The house was built in 1990."],structure:7,explain:{why:"PP de <em>build</em> : <strong>built</strong> (irrégulier). Cas classique du passif : le constructeur est inconnu ou sans intérêt — c'est la date qui compte.",active:{en:"They built the house in 1990.",fr:"Ils ont construit la maison en 1990."}}},
      {fr:"Le message a été lu.",en:["The message was read."],structure:7,explain:{why:"PP de <em>read</em> : <strong>read</strong> — même orthographe que l'infinitif, mais prononciation différente ! Au passé, ça se dit [rɛd], comme le mot <em>red</em> (rouge).",active:{en:"Someone read the message.",fr:"Quelqu'un a lu le message."}}},
      {fr:"Le gâteau a été mangé.",en:["The cake was eaten."],structure:7,explain:{why:"PP de <em>eat</em> : <strong>eaten</strong> (irrégulier : eat → ate → eaten). Situation classique où on constate le résultat sans savoir qui a agi.",active:{en:"Someone ate the cake.",fr:"Quelqu'un a mangé le gâteau."}}},
      {fr:"La décision a été prise hier.",en:["The decision was made yesterday.","The decision was taken yesterday."],structure:7,variantNote:"Même sens — <em>made</em> est plus courant, <em>taken</em> aussi correct.",explain:{why:"On dit <em>make a decision</em> (plus naturel) ou <em>take a decision</em>. Les deux se mettent au passif sans problème. <em>Made</em> reste le plus fréquent.",active:{en:"They made the decision yesterday.",fr:"Ils ont pris la décision hier."}}},
      {fr:"Le pont a été construit par des ingénieurs.",en:["The bridge was built by engineers."],structure:7,explain:{why:"<strong>bridge</strong> = pont — à retenir ! Ici on précise l'auteur avec <strong>by engineers</strong> car c'est une info importante. Le <em>by</em> est optionnel au passif — on l'ajoute seulement si ça apporte quelque chose.",active:{en:"Engineers built the bridge.",fr:"Des ingénieurs ont construit le pont."}}},
      {fr:"Les règles sont respectées ici.",en:["The rules are followed here.","The rules are obeyed here."],structure:7,variantNote:"<em>follow the rules</em> et <em>obey the rules</em> signifient tous les deux respecter les règles. <em>Obey</em> insiste davantage sur l'obéissance.",explain:{why:"Présent simple passif (pluriel) : <strong>are + PP</strong>. <em>follow the rules</em> = respecter les règles — expression à retenir, plus naturelle que <em>respect</em> en anglais.",active:{en:"People follow the rules here.",fr:"Les gens respectent les règles ici."}}},
      {fr:"Le contrat a été signé ce matin.",en:["The contract was signed this morning."],structure:7,explain:{why:"<strong>contract</strong> = contrat — même mot, même orthographe ! <em>signed</em> est régulier (sign → signed). <em>this morning</em> = ce matin.",active:{en:"They signed the contract this morning.",fr:"Ils ont signé le contrat ce matin."}}},
      {fr:"Les résultats seront annoncés demain.",en:["The results will be announced tomorrow."],structure:7,explain:{why:"Futur passif : <strong>will be + PP</strong> — formule à retenir ! <strong>announced</strong> = annoncé (regular : announce → announced). Attention au double <em>n</em>.",active:{en:"They will announce the results tomorrow.",fr:"Ils annonceront les résultats demain."}}},
      {fr:"Ce tableau a été peint au 17ème siècle.",en:["This painting was painted in the 17th century."],structure:7,explain:{why:"<strong>painting</strong> = tableau ou peinture. PP de <em>paint</em> : <strong>painted</strong> (régulier). <em>17th century</em> = 17ème siècle — les siècles s'écrivent en chiffres ordinaux en anglais.",active:{en:"An artist painted this in the 17th century.",fr:"Un artiste a peint cela au 17ème siècle."}}},
      {fr:"Le suspect a été arrêté par la police.",en:["The suspect was arrested by the police."],structure:7,explain:{why:"<strong>arrested</strong> = arrêté (regular : arrest → arrested). On ajoute <em>by the police</em> car c'est une info utile — ça explique comment c'est arrivé.",active:{en:"The police arrested the suspect.",fr:"La police a arrêté le suspect."}}},
      {fr:"Les billets ont été vendus en quelques minutes.",en:["The tickets were sold in a few minutes."],structure:7,explain:{why:"PP de <em>sell</em> : <strong>sold</strong> (irrégulier). <strong>in a few minutes</strong> = en quelques minutes — à retenir ! <em>tickets</em> au pluriel → <em>were</em> (pas <em>was</em>).",active:{en:"They sold the tickets in a few minutes.",fr:"Ils ont vendu les billets en quelques minutes."}}},
      {fr:"Le problème a été résolu.",en:["The problem was solved.","The problem has been solved."],structure:7,variantNote:"<em>was solved</em> = passé simple passif (fait terminé). <em>has been solved</em> = present perfect passif — le problème est résolu et ça compte encore maintenant.",explain:{why:"<em>solved</em> est régulier (solve → solved). Le choix entre <em>was solved</em> et <em>has been solved</em> dépend du contexte : passé terminé vs résultat présent.",active:{en:"Someone solved the problem.",fr:"Quelqu'un a résolu le problème."}}},
      {fr:"Ces chaussures sont fabriquées en Italie.",en:["These shoes are made in Italy."],structure:7,explain:{why:"Présent simple passif (pluriel) : <strong>are + PP</strong>. <strong>made in</strong> = fabriqué en — expression qu'on lit sur l'étiquette de tous les produits, partout dans le monde !",active:{en:"They make these shoes in Italy.",fr:"Ils fabriquent ces chaussures en Italie."}}},
      {fr:"La réunion a été annulée.",en:["The meeting was cancelled.","The meeting was canceled."],structure:7,variantNote:"<em>cancelled</em> = orthographe britannique, <em>canceled</em> = orthographe américaine. Les deux sont correctes.",explain:{why:"<strong>meeting</strong> = réunion — mot très fréquent en anglais pro, à retenir ! <em>cancelled</em> (UK) ou <em>canceled</em> (US) — même mot, deux façons d'écrire.",active:{en:"They cancelled the meeting.",fr:"Ils ont annulé la réunion."}}},
      {fr:"Le film a été tourné à Los Angeles.",en:["The movie was filmed in Los Angeles.","The movie was shot in Los Angeles."],structure:7,variantNote:"<em>filmed</em> est le terme neutre. <em>shot</em> (PP de <em>shoot</em>) est plus courant dans l'industrie cinéma — à retenir !",explain:{why:"PP de <em>shoot</em> : <strong>shot</strong> (irrégulier : shoot → shot → shot). Dans le cinéma, on dit <em>shoot a film</em> plutôt que <em>film a film</em>. <em>movie</em> (US) = <em>film</em> (UK).",active:{en:"They shot the movie in Los Angeles.",fr:"Ils ont tourné le film à Los Angeles."}}},
      {fr:"L'email a été envoyé à tous les employés.",en:["The email was sent to all the employees."],structure:7,explain:{why:"<strong>employees</strong> = les employés — à retenir ! PP de <em>send</em> : <strong>sent</strong> (irrégulier). <em>to all the employees</em> = à tous les employés.",active:{en:"Someone sent the email to all the employees.",fr:"Quelqu'un a envoyé l'email à tous les employés."}}},
      {fr:"Le voleur a été condamné à deux ans de prison.",en:["The thief was sentenced to two years in prison."],structure:7,explain:{why:"<strong>sentenced to</strong> = condamné à — expression à retenir absolument ! <em>in prison</em> = en prison. Le juge n'est pas mentionné — c'est le résultat qui compte.",active:{en:"The judge sentenced the thief to two years in prison.",fr:"Le juge a condamné le voleur à deux ans de prison."}}},
      {fr:"La nouvelle a été partagée sur les réseaux sociaux.",en:["The news was shared on social media."],structure:7,explain:{why:"<strong>news</strong> est toujours singulier en anglais — jamais <em>a news</em> ni <em>newses</em> ! On dit <em>a piece of news</em> pour une seule info. <em>social media</em> = les réseaux sociaux.",active:{en:"Someone shared the news on social media.",fr:"Quelqu'un a partagé la nouvelle sur les réseaux sociaux."}}},
      {fr:"Ce roman a été traduit en vingt langues.",en:["This novel was translated into 20 languages."],structure:7,explain:{why:"<strong>translated into</strong> — la préposition <em>into</em> (et pas <em>in</em> !) s'impose après <em>translate</em>. <strong>novel</strong> = roman — à retenir !",active:{en:"They translated this novel into 20 languages.",fr:"Ils ont traduit ce roman en vingt langues."}}},
      {fr:"Les blessés ont été transportés à l'hôpital.",en:["The injured were taken to the hospital."],structure:7,explain:{why:"<strong>the injured</strong> = les blessés. En anglais, <strong>the + adjectif</strong> peut désigner tout un groupe : <em>the rich</em> (les riches), <em>the homeless</em> (les sans-abri)… Construction à retenir !",active:{en:"They took the injured to the hospital.",fr:"Ils ont transporté les blessés à l'hôpital."}}},
      {fr:"Le rapport a été rédigé par le directeur.",en:["The report was written by the manager.","The report was written by the director."],structure:7,variantNote:"<em>manager</em> = responsable direct (chef d'équipe). <em>director</em> = directeur, plus haut dans la hiérarchie.",explain:{why:"<strong>report</strong> = rapport — à retenir ! On ajoute <em>by the manager</em> car ici l'auteur est une info importante — ça change la valeur du document.",active:{en:"The manager wrote the report.",fr:"Le directeur a rédigé le rapport."}}},
      {fr:"La fête a été organisée par ses amis.",en:["The party was organised by her friends.","The party was organized by her friends."],structure:7,variantNote:"<em>organised</em> = orthographe britannique, <em>organized</em> = américaine. Les deux sont correctes.",explain:{why:"On précise <em>by her friends</em> car c'est une info touchante — ça donne un sens émotionnel à la phrase. Le <em>by + agent</em> n'est utile que quand il apporte quelque chose.",active:{en:"Her friends organised the party.",fr:"Ses amis ont organisé la fête."}}},
      {fr:"Le médicament a été approuvé par les autorités.",en:["The medicine was approved by the authorities."],structure:7,explain:{why:"<strong>approved</strong> = approuvé — à retenir ! <strong>authorities</strong> = les autorités. <em>medicine</em> = médicament (aussi : <em>drug</em> dans un contexte médical ou scientifique).",active:{en:"The authorities approved the medicine.",fr:"Les autorités ont approuvé le médicament."}}},
      {fr:"Ce musée est visité par des millions de personnes chaque année.",en:["This museum is visited by millions of people every year."],structure:7,explain:{why:"<strong>museum</strong> = musée — à retenir ! Présent simple passif : <strong>is + PP</strong>. Attention : <em>millions of people</em> (avec <em>of</em>), mais <em>two million people</em> sans <em>of</em> quand il y a un chiffre précis.",active:{en:"Millions of people visit this museum every year.",fr:"Des millions de personnes visitent ce musée chaque année."}}},
      {fr:"Une médaille lui a été remise.",en:["A medal was given to him.","A medal was given to her."],structure:7,variantNote:"<em>him</em> = à lui, <em>her</em> = à elle — les deux sont corrects selon la personne.",explain:{why:"PP de <em>give</em> : <strong>given</strong> (irrégulier : give → gave → given). <em>given to</em> = remis à. On met la médaille en valeur — QUI la remet est secondaire.",active:{en:"They gave him a medal.",fr:"Ils lui ont remis une médaille."}}},
      {fr:"Le portefeuille a été retrouvé.",en:["The wallet was found."],structure:7,explain:{why:"PP de <em>find</em> : <strong>found</strong> (irrégulier : find → found → found). <strong>wallet</strong> = portefeuille — à retenir ! On ne sait pas qui l'a trouvé — c'est le résultat qui compte.",active:{en:"Someone found the wallet.",fr:"Quelqu'un a retrouvé le portefeuille."}}},
      {fr:"Le gagnant a été choisi.",en:["The winner was chosen."],structure:7,explain:{why:"PP de <em>choose</em> : <strong>chosen</strong> (irrégulier : choose → chose → chosen). <strong>winner</strong> = gagnant — à retenir ! On ne précise pas QUI a choisi — classique dans un concours.",active:{en:"The jury chose the winner.",fr:"Le jury a choisi le gagnant."}}},
      {fr:"Trois langues sont parlées dans ce pays.",en:["Three languages are spoken in this country."],structure:7,explain:{why:"PP de <em>speak</em> : <strong>spoken</strong> (irrégulier : speak → spoke → spoken). Présent simple passif pluriel : <strong>are + PP</strong>. Phrase très naturelle — on ne dit pas qui parle, c'est un fait général.",active:{en:"People speak three languages in this country.",fr:"Les gens parlent trois langues dans ce pays."}}},
      {fr:"Cette matière est enseignée dans toutes les écoles.",en:["This subject is taught in every school."],structure:7,explain:{why:"PP de <em>teach</em> : <strong>taught</strong> (irrégulier : teach → taught → taught). <strong>subject</strong> = matière scolaire — à retenir ! <em>every school</em> = toutes les écoles (sans article).",active:{en:"Teachers teach this subject in every school.",fr:"Les professeurs enseignent cette matière dans toutes les écoles."}}},
      {fr:"Ce chanteur est connu dans le monde entier.",en:["This singer is known all over the world."],structure:7,explain:{why:"PP de <em>know</em> : <strong>known</strong> (irrégulier : know → knew → known). <strong>all over the world</strong> = dans le monde entier — expression très courante à retenir !",active:{en:"Everyone knows this singer.",fr:"Tout le monde connaît ce chanteur."}}},
      {fr:"Ce film a été vu par des millions de personnes.",en:["This movie was seen by millions of people."],structure:7,explain:{why:"PP de <em>see</em> : <strong>seen</strong> (irrégulier : see → saw → seen). On ajoute <em>by millions of people</em> car c'est une info impressionnante qui justifie de mentionner l'agent.",active:{en:"Millions of people saw this movie.",fr:"Des millions de personnes ont vu ce film."}}},
      {fr:"Cette carte a été dessinée à la main.",en:["This map was drawn by hand."],structure:7,explain:{why:"PP de <em>draw</em> : <strong>drawn</strong> (irrégulier : draw → drew → drawn). <strong>map</strong> = carte géographique — à retenir ! <strong>by hand</strong> = à la main — expression très utile.",active:{en:"Someone drew this map by hand.",fr:"Quelqu'un a dessiné cette carte à la main."}}},
      {fr:"Les résultats lui ont été montrés.",en:["The results were shown to him.","The results were shown to her."],structure:7,variantNote:"<em>him</em> = à lui, <em>her</em> = à elle — les deux corrects selon le contexte.",explain:{why:"PP de <em>show</em> : <strong>shown</strong> (irrégulier : show → showed → shown). <em>shown to</em> = montré à. On met les résultats en valeur — QUI les a montrés est secondaire.",active:{en:"Someone showed him the results.",fr:"Quelqu'un lui a montré les résultats."}}},
      {fr:"Le match a été gagné grâce à un seul but.",en:["The match was won thanks to a single goal."],structure:7,explain:{why:"PP de <em>win</em> : <strong>won</strong> (irrégulier : win → won → won). <strong>thanks to</strong> = grâce à — expression à retenir. <strong>goal</strong> = but au football. On insiste sur le match, pas sur l'équipe.",active:{en:"They won the match thanks to a single goal.",fr:"Ils ont gagné le match grâce à un seul but."}}},
      {fr:"La vérité lui a été dite.",en:["The truth was told to him.","He was told the truth."],structure:7,variantNote:"Deux constructions passives : <em>the truth was told to him</em> (l'objet direct devient sujet) ou <em>he was told the truth</em> (l'objet indirect devient sujet). Les deux sont correctes.",explain:{why:"PP de <em>tell</em> : <strong>told</strong> (irrégulier : tell → told → told). Cas rare en anglais : deux structures passives possibles pour la même phrase active !",active:{en:"Someone told him the truth.",fr:"Quelqu'un lui a dit la vérité."}}},
      {fr:"Les travailleurs ont été payés vendredi.",en:["The workers were paid on Friday."],structure:7,explain:{why:"PP de <em>pay</em> : <strong>paid</strong> (irrégulier : pay → paid → paid). <strong>workers</strong> = travailleurs — à retenir ! <em>on Friday</em> = vendredi (on + jour de la semaine).",active:{en:"The company paid the workers on Friday.",fr:"L'entreprise a payé les travailleurs vendredi."}}},
      {fr:"La cérémonie a été tenue à Paris.",en:["The ceremony was held in Paris."],structure:7,explain:{why:"PP de <em>hold</em> : <strong>held</strong> (irrégulier : hold → held → held). <em>hold an event</em> = tenir/organiser un événement — sens différent de 'tenir dans la main' ! <strong>ceremony</strong> = cérémonie.",active:{en:"They held the ceremony in Paris.",fr:"Ils ont tenu la cérémonie à Paris."}}},
      {fr:"Ces vêtements n'ont jamais été portés.",en:["These clothes have never been worn."],structure:7,explain:{why:"PP de <em>wear</em> : <strong>worn</strong> (irrégulier : wear → wore → worn). Present perfect passif : <strong>have been + PP</strong>. <strong>clothes</strong> est toujours pluriel en anglais — jamais <em>a clothe</em> !",active:{en:"Nobody has ever worn these clothes.",fr:"Personne n'a jamais porté ces vêtements."}}},
      {fr:"Le ballon a été lancé trop fort.",en:["The ball was thrown too hard."],structure:7,explain:{why:"PP de <em>throw</em> : <strong>thrown</strong> (irrégulier : throw → threw → thrown). <strong>too hard</strong> = trop fort — à retenir ! <em>hard</em> peut être adjectif (dur) ou adverbe (fort, difficilement).",active:{en:"Someone threw the ball too hard.",fr:"Quelqu'un a lancé le ballon trop fort."}}},
      {fr:"Ses instructions n'ont pas été comprises.",en:["His instructions were not understood.","His instructions weren't understood."],structure:7,variantNote:"<em>weren't</em> est la contraction de <em>were not</em> — plus naturelle à l'oral.",explain:{why:"PP de <em>understand</em> : <strong>understood</strong> (irrégulier : understand → understood → understood). Instructions au pluriel → <em>were not</em>. Phrase utile pour parler d'un problème de communication.",active:{en:"Nobody understood his instructions.",fr:"Personne n'a compris ses instructions."}}},
      {fr:"Son nom a été oublié avec le temps.",en:["His name was forgotten over time."],structure:7,explain:{why:"PP de <em>forget</em> : <strong>forgotten</strong> (irrégulier : forget → forgot → forgotten). <strong>over time</strong> = avec le temps — expression naturelle à retenir ! Le passif renforce l'idée que ça s'est passé sans que personne ne le décide.",active:{en:"People forgot his name over time.",fr:"Les gens ont oublié son nom avec le temps."}}},
      {fr:"Un message a été laissé sur le répondeur.",en:["A message was left on the answering machine."],structure:7,explain:{why:"PP de <em>leave</em> : <strong>left</strong> (irrégulier : leave → left → left). <strong>answering machine</strong> = répondeur — à retenir ! <em>leave a message</em> = laisser un message, expression très courante.",active:{en:"Someone left a message on the answering machine.",fr:"Quelqu'un a laissé un message sur le répondeur."}}},
      {fr:"Les documents ont été perdus pendant le déménagement.",en:["The documents were lost during the move."],structure:7,explain:{why:"PP de <em>lose</em> : <strong>lost</strong> (irrégulier : lose → lost → lost). <strong>during the move</strong> = pendant le déménagement. <strong>move</strong> = déménagement — à retenir ! Le passif s'impose car on ne sait pas qui les a perdus.",active:{en:"Someone lost the documents during the move.",fr:"Quelqu'un a perdu les documents pendant le déménagement."}}},
      {fr:"La voiture a été conduite par un chauffeur professionnel.",en:["The car was driven by a professional driver."],structure:7,explain:{why:"PP de <em>drive</em> : <strong>driven</strong> (irrégulier : drive → drove → driven). <strong>driver</strong> = chauffeur/conducteur — à retenir ! On ajoute <em>by a professional driver</em> car c'est une info utile sur la qualité.",active:{en:"A professional driver drove the car.",fr:"Un chauffeur professionnel a conduit la voiture."}}}
    ]
  },
  "prepositions-1": {
    id: "prepositions-1",
    title: "Prépositions de lieu",
    subtitle: "AT / ON / IN — L'Espace",
    icon: "📍",
    color: "#10b981",
    questionCount: 15,
    theoryPage: "theory-prepositions.html",
    hasQuiz: true,
    questions: []
  },
  "phrasal-hub": {
    id:"phrasal-hub",
    title:"Phrasal Verbs",
    subtitle:"Théorie, liste complète & exercices",
    icon:"🔗",
    color:"#8b5cf6",
    theoryPage:"phrasal-hub.html",
    hasQuiz:true
  },
  "phrasal-theory": {
    id:"phrasal-theory",hidden:true,
    title:"Comprendre les phrasal verbs",
    subtitle:"Définition, types & liste complète",
    icon:"📖",
    color:"#8b5cf6",
    theoryPage:"theory-phrasal-verbs.html"
  },
  "phrasal-1": {
    id:"phrasal-1",hidden:true,
    title:"Phrasal Verbs — Pack 1",
    subtitle:"Les 10 essentiels du quotidien",
    icon:"🔗",color:"#8b5cf6",questionCount:10,hasQuiz:true,
    questions:[
      {fr:"abandonner",en:["give up"]},
      {fr:"chercher",en:["look for"]},
      {fr:"découvrir / apprendre (une info)",en:["find out"]},
      {fr:"tomber sur quelqu'un (par hasard)",en:["run into"]},
      {fr:"continuer",en:["carry on"]},
      {fr:"reporter / remettre à plus tard",en:["put off"]},
      {fr:"décevoir",en:["let down"]},
      {fr:"finir par",en:["end up"]},
      {fr:"se lever",en:["get up"]},
      {fr:"ramasser / aller chercher",en:["pick up"]}
    ]
  },
  "phrasal-2": {
    id:"phrasal-2",hidden:true,
    title:"Phrasal Verbs — Pack 2",
    subtitle:"10 expressions avancées",
    icon:"🔗",color:"#7c3aed",questionCount:10,hasQuiz:true,
    questions:[
      {fr:"allumer",en:["turn on"]},
      {fr:"éteindre",en:["turn off"]},
      {fr:"jeter",en:["throw away"]},
      {fr:"refuser / baisser le volume",en:["turn down"]},
      {fr:"tomber en panne / craquer",en:["break down"]},
      {fr:"s'entraîner / se passer bien",en:["work out"]},
      {fr:"avoir hâte de",en:["look forward to"]},
      {fr:"manquer de / ne plus avoir",en:["run out of"]},
      {fr:"surmonter / se remettre de",en:["get over"]},
      {fr:"mettre en place / créer",en:["set up"]}
    ]
  },
  "phrasal-phrases-1": {
    id:"phrasal-phrases-1",hidden:true,
    title:"Phrasal Verbs en phrases",
    subtitle:"Traduis des phrases complètes",
    icon:"💬",color:"#6d28d9",questionCount:20,hasQuiz:true,
    questions:[
      {fr:"J'ai abandonné le sport l'année dernière.",en:["I gave up sport last year."]},
      {fr:"Elle cherche ses clés depuis ce matin.",en:["She has been looking for her keys since this morning.","She's been looking for her keys since this morning."]},
      {fr:"J'ai découvert qu'il avait menti.",en:["I found out that he had lied.","I found out he had lied."]},
      {fr:"Je suis tombé sur mon prof au supermarché.",en:["I ran into my teacher at the supermarket."]},
      {fr:"Continue, tu fais du bon travail.",en:["Carry on, you're doing a great job.","Carry on, you are doing a great job."]},
      {fr:"Il a encore reporté notre réunion.",en:["He put off our meeting again.","He put our meeting off again."]},
      {fr:"Tu m'as vraiment déçu cette fois.",en:["You really let me down this time."]},
      {fr:"On a fini par prendre un taxi.",en:["We ended up taking a taxi."]},
      {fr:"Elle se lève à 6h tous les matins.",en:["She gets up at 6 every morning.","She gets up at 6 am every morning."]},
      {fr:"Tu peux venir me chercher à la gare ?",en:["Can you pick me up at the station?","Could you pick me up at the station?"]},
      {fr:"Allume la télé, s'il te plaît.",en:["Turn on the TV, please.","Turn the TV on, please."]},
      {fr:"N'oublie pas d'éteindre la lumière.",en:["Don't forget to turn off the light.","Don't forget to turn the light off."]},
      {fr:"Il a jeté tous ses vieux livres.",en:["He threw away all his old books.","He threw all his old books away."]},
      {fr:"Elle a refusé notre offre.",en:["She turned down our offer.","She turned our offer down."]},
      {fr:"Ma voiture est tombée en panne hier.",en:["My car broke down yesterday."]},
      {fr:"Ça ne s'est pas passé comme prévu.",en:["It didn't work out as planned."]},
      {fr:"J'ai vraiment hâte de te voir.",en:["I'm really looking forward to seeing you.","I am really looking forward to seeing you."]},
      {fr:"On n'a plus de café.",en:["We have run out of coffee.","We've run out of coffee.","We ran out of coffee."]},
      {fr:"Il s'est vite remis de sa blessure.",en:["He quickly got over his injury."]},
      {fr:"Ils ont créé une nouvelle entreprise.",en:["They set up a new company.","They set a new company up."]}
    ]
  }
};