const LESSONS = {
  "structures-1": {
    id: "structures-1",
    title: "Structures Clés",
    subtitle: "Would, Could, Should",
    icon: "🏗️",
    color: "#3b82f6",
    questionCount: 25,
    theoryPage: "theory-structures.html",
    hasQuiz: true,
    questions: [
      {fr:"Je voudrais un café, s'il vous plaît.",en:["I would like a coffee, please."],structure:1},
      {fr:"Est-ce que tu voudrais venir avec nous ?",en:["Would you like to come with us?"],structure:1},
      {fr:"Il aimerait apprendre le piano.",en:["He would like to learn the piano.","He would love to learn the piano."],structure:1,variantNote:"Même sens — <em>love</em> exprime une intensité légèrement plus forte que <em>like</em>."},
      {fr:"Nous voudrions réserver une table pour ce soir.",en:["We would like to book a table for tonight.","We would like to reserve a table for tonight."],structure:1,variantNote:"Synonymes — <em>book</em> et <em>reserve</em> signifient tous les deux réserver, aucune différence de sens."},
      {fr:"Elle préférerait rester à la maison.",en:["She would prefer to stay at home.","She would rather stay at home."],structure:1,variantNote:"Même sens, construction différente — <em>would prefer + to + verbe</em>, mais <em>would rather + infinitif sans to</em>."},
      {fr:"Je veux vraiment aller à Paris un jour.",en:["I would really like to go to Paris one day.","I really want to go to Paris one day."],structure:1,variantNote:"Légère différence de registre — <em>would like</em> est plus poli et formel, <em>want</em> est plus direct et décontracté."},
      {fr:"Ils voudraient un remboursement.",en:["They would like a refund."],structure:1},
      {fr:"Est-ce que vous voudriez quelque chose à boire ?",en:["Would you like something to drink?"],structure:1},
      {fr:"J'aimerais vraiment te voir bientôt.",en:["I would really like to see you soon.","I would love to see you soon."],structure:1,variantNote:"Même sens — <em>love</em> ajoute une touche d'enthousiasme plus forte, mais les deux sont tout à fait correctes."},
      {fr:"Pourriez-vous m'aider, s'il vous plaît ?",en:["Could you help me, please?"],structure:2},
      {fr:"Est-ce que tu pourrais fermer la fenêtre ?",en:["Could you close the window?","Could you please close the window?"],structure:2,variantNote:"Aucune différence — <em>please</em> renforce simplement la politesse, il est optionnel."},
      {fr:"Serait-il possible de changer ma réservation ?",en:["Could I change my reservation?","Would it be possible to change my reservation?"],structure:2,variantNote:"<em>Could I…</em> est direct et courant. <em>Would it be possible…</em> est plus formel, souvent utilisé dans un contexte professionnel."},
      {fr:"Pourriez-vous parler plus lentement ?",en:["Could you speak more slowly?","Could you please speak more slowly?"],structure:2,variantNote:"Aucune différence — <em>please</em> est optionnel, il renforce la politesse."},
      {fr:"Est-ce que je pourrais avoir l'addition ?",en:["Could I have the bill?","Could I get the check?"],structure:2,variantNote:"Différence géographique uniquement — <em>bill</em> est anglais britannique, <em>check</em> est américain. Même sens !"},
      {fr:"Ce serait bien si tu pouvais venir.",en:["It would be nice if you could come."],structure:2},
      {fr:"Pourrait-il rappeler plus tard ?",en:["Could he call back later?"],structure:2},
      {fr:"Est-ce que tu pourrais me prêter ton stylo ?",en:["Could you lend me your pen?","Could you borrow me your pen?"],structure:2,variantNote:"<em>lend</em> = prêter (tu donnes), <em>borrow</em> = emprunter (tu reçois). Ici <em>lend me</em> est la formulation correcte — <em>Could you borrow me</em> n'est pas standard en anglais."},
      {fr:"J'aurais dû étudier plus tôt.",en:["I should have studied earlier."],structure:3},
      {fr:"Il aurait dû appeler avant de venir.",en:["He should have called before coming."],structure:3},
      {fr:"Nous aurions dû prendre un parapluie.",en:["We should have taken an umbrella.","We should have brought an umbrella."],structure:3,variantNote:"Très proches — <em>taken</em> (pris) vs <em>brought</em> (apporté/amené). <em>Brought</em> est légèrement plus naturel car on insiste sur le fait d'amener l'objet avec soi."},
      {fr:"Tu n'aurais pas dû dire ça.",en:["You should not have said that.","You shouldn't have said that."],structure:3,variantNote:"Aucune différence — <em>shouldn't</em> est la contraction de <em>should not</em>, plus courante à l'oral."},
      {fr:"Elle aurait dû partir plus tôt.",en:["She should have left earlier."],structure:3},
      {fr:"Ils auraient dû lire les instructions.",en:["They should have read the instructions."],structure:3},
      {fr:"J'aurais dû me souvenir de son anniversaire.",en:["I should have remembered her birthday.","I should have remembered his birthday."],structure:3,variantNote:"Aucune différence de sens — <em>her</em> = son (féminin), <em>his</em> = son (masculin). Dépend de la personne dont tu parles."},
      {fr:"On aurait dû réserver à l'avance.",en:["We should have booked in advance.","We should have reserved in advance."],structure:3,variantNote:"Synonymes — <em>book</em> et <em>reserve</em> signifient tous les deux réserver, aucune différence de sens."}
    ]
  },
  "past-participle-1": {
    id: "past-participle-1",
    title: "Participe Passé",
    subtitle: "Formation & 4 structures essentielles",
    icon: "⏪",
    color: "#10b981",
    questionCount: 20,
    theoryPage: "theory-past-participle.html",
    hasQuiz: true,
    questions: [
      {fr:"J'ai mangé.",en:["I have eaten."],structure:4},
      {fr:"Elle a fini son travail.",en:["She has finished her work."],structure:4},
      {fr:"Il a cassé la fenêtre.",en:["He has broken the window."],structure:4},
      {fr:"Tu as oublié tes clés.",en:["You have forgotten your keys."],structure:4},
      {fr:"Nous avons pris notre décision.",en:["We have made our decision.","We have taken our decision."],structure:4,variantNote:"<em>make a decision</em> est plus naturel en anglais courant, <em>take a decision</em> est aussi correct."},
      {fr:"Il avait déjà mangé quand je suis arrivé.",en:["He had already eaten when I arrived."],structure:5},
      {fr:"Elle avait étudié toute la nuit.",en:["She had studied all night."],structure:5},
      {fr:"Nous avions déjà vu ce film.",en:["We had already seen this movie.","We had already seen this film."],structure:5,variantNote:"Aucune différence — <em>movie</em> est américain, <em>film</em> est britannique."},
      {fr:"Ils n'avaient jamais voyagé à l'étranger.",en:["They had never travelled abroad.","They had never traveled abroad."],structure:5,variantNote:"Aucune différence — <em>travelled</em> est l'orthographe britannique, <em>traveled</em> est américaine."},
      {fr:"Tu aurais dû appeler.",en:["You should have called."],structure:6},
      {fr:"Elle aurait pu venir.",en:["She could have come."],structure:6},
      {fr:"Il a dû oublier son rendez-vous.",en:["He must have forgotten his appointment."],structure:6},
      {fr:"Nous aurions pu rester.",en:["We could have stayed."],structure:6},
      {fr:"Elle aurait dû savoir.",en:["She should have known."],structure:6},
      {fr:"La fenêtre a été cassée.",en:["The window was broken."],structure:7},
      {fr:"La lettre a été envoyée.",en:["The letter was sent."],structure:7},
      {fr:"Le livre a été écrit en 1984.",en:["The book was written in 1984."],structure:7},
      {fr:"Le repas est préparé.",en:["The meal is prepared."],structure:7},
      {fr:"La décision a été prise.",en:["The decision was made.","The decision was taken."],structure:7,variantNote:"Même sens — <em>made</em> est plus courant, <em>taken</em> aussi correct."},
      {fr:"Les instructions n'ont pas été suivies.",en:["The instructions were not followed.","The instructions weren't followed."],structure:7,variantNote:"Aucune différence — <em>weren't</em> est la contraction de <em>were not</em>."}
    ]
  },
  "prepositions-1": {
    id: "prepositions-1",
    title: "Prépositions de lieu",
    subtitle: "AT / ON / IN — L'Espace",
    icon: "📍",
    color: "#10b981",
    questionCount: 15,
    theoryPage: "theory-prepositions.html",
    hasQuiz: true,
    questions: []
  }
};